"""Teams, games and bets tables

Revision ID: 3caba0496e12
Revises: b7d343186ff4
Create Date: 2019-11-26 21:59:11.432584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3caba0496e12'
down_revision = 'b7d343186ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('short_name', sa.String(length=3), nullable=False),
    sa.Column('long_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('short_name'),
    sa.UniqueConstraint('long_name')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=3), nullable=True),
    sa.Column('away_team', sa.String(length=3), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['away_team'], ['team.short_name'], ),
    sa.ForeignKeyConstraint(['home_team'], ['team.short_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_timestamp'), 'game', ['timestamp'], unique=False)
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('bet_on_home', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_game_id'), 'bet', ['game_id'], unique=False)
    op.create_index(op.f('ix_bet_timestamp'), 'bet', ['timestamp'], unique=False)
    op.create_index(op.f('ix_bet_user_id'), 'bet', ['user_id'], unique=False)
    op.add_column('user', sa.Column('funds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'funds')
    op.drop_index(op.f('ix_bet_user_id'), table_name='bet')
    op.drop_index(op.f('ix_bet_timestamp'), table_name='bet')
    op.drop_index(op.f('ix_bet_game_id'), table_name='bet')
    op.drop_table('bet')
    op.drop_index(op.f('ix_game_timestamp'), table_name='game')
    op.drop_table('game')
    op.drop_table('team')
    # ### end Alembic commands ###
