"""empty message

Revision ID: 5d94da9f71eb
Revises: 
Create Date: 2019-11-28 01:19:14.414053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d94da9f71eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('short_name', sa.String(length=3), nullable=False),
    sa.Column('long_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('short_name'),
    sa.UniqueConstraint('long_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('funds', sa.Integer(), nullable=True),
    sa.Column('date_reg', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=3), nullable=True),
    sa.Column('away_team', sa.String(length=3), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['away_team'], ['team.short_name'], ),
    sa.ForeignKeyConstraint(['home_team'], ['team.short_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('home_team', 'away_team', 'date')
    )
    op.create_index(op.f('ix_game_date'), 'game', ['date'], unique=False)
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('bet_on_home', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_game_id'), 'bet', ['game_id'], unique=False)
    op.create_index(op.f('ix_bet_timestamp'), 'bet', ['timestamp'], unique=False)
    op.create_index(op.f('ix_bet_user_id'), 'bet', ['user_id'], unique=False)
    op.create_table('finished_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finished_bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['bet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finished_bet')
    op.drop_table('finished_game')
    op.drop_index(op.f('ix_bet_user_id'), table_name='bet')
    op.drop_index(op.f('ix_bet_timestamp'), table_name='bet')
    op.drop_index(op.f('ix_bet_game_id'), table_name='bet')
    op.drop_table('bet')
    op.drop_index(op.f('ix_game_date'), table_name='game')
    op.drop_table('game')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('team')
    # ### end Alembic commands ###
