"""empty message

Revision ID: 3fc5cee2eeaf
Revises: 5783a8e2541b
Create Date: 2019-12-06 13:54:31.460847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc5cee2eeaf'
down_revision = '5783a8e2541b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_index(op.f('ix_user_ranking_funds'), 'user', ['ranking_funds'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ranking_funds'), table_name='user')
    op.drop_table('followers')
    # ### end Alembic commands ###
