"""empty message

Revision ID: 5783a8e2541b
Revises: 765473082525
Create Date: 2019-12-05 16:34:29.594621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5783a8e2541b'
down_revision = '765473082525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timestamp_games', sa.Column('api_remaining', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timestamp_games', 'api_remaining')
    # ### end Alembic commands ###
