"""lol

Revision ID: 663791e39584
Revises: 
Create Date: 2020-01-21 20:56:14.319397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663791e39584'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('short_name', sa.String(length=3), nullable=False),
    sa.Column('long_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('short_name'),
    sa.UniqueConstraint('long_name')
    )
    op.create_table('timestamp_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('api_remaining', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timestamp_games_timestamp'), 'timestamp_games', ['timestamp'], unique=False)
    op.create_table('timestamp_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timestamp_scores_timestamp'), 'timestamp_scores', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('funds', sa.Integer(), nullable=True),
    sa.Column('ranking_funds', sa.Integer(), nullable=True),
    sa.Column('date_reg', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_ranking_funds'), 'user', ['ranking_funds'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=3), nullable=True),
    sa.Column('away_team', sa.String(length=3), nullable=True),
    sa.Column('home_odds', sa.Float(), nullable=True),
    sa.Column('away_odds', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('date_time', sa.String(length=40), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['away_team'], ['team.short_name'], ),
    sa.ForeignKeyConstraint(['home_team'], ['team.short_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('home_team', 'away_team', 'date')
    )
    op.create_index(op.f('ix_game_date'), 'game', ['date'], unique=False)
    op.create_index(op.f('ix_game_date_time'), 'game', ['date_time'], unique=False)
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('bet_on_home', sa.Boolean(), nullable=True),
    sa.Column('date_time', sa.String(length=40), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', 'bet_on_home')
    )
    op.create_index(op.f('ix_bet_date_time'), 'bet', ['date_time'], unique=False)
    op.create_index(op.f('ix_bet_game_id'), 'bet', ['game_id'], unique=False)
    op.create_index(op.f('ix_bet_user_id'), 'bet', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bet_user_id'), table_name='bet')
    op.drop_index(op.f('ix_bet_game_id'), table_name='bet')
    op.drop_index(op.f('ix_bet_date_time'), table_name='bet')
    op.drop_table('bet')
    op.drop_index(op.f('ix_game_date_time'), table_name='game')
    op.drop_index(op.f('ix_game_date'), table_name='game')
    op.drop_table('game')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_ranking_funds'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_timestamp_scores_timestamp'), table_name='timestamp_scores')
    op.drop_table('timestamp_scores')
    op.drop_index(op.f('ix_timestamp_games_timestamp'), table_name='timestamp_games')
    op.drop_table('timestamp_games')
    op.drop_table('team')
    # ### end Alembic commands ###
