"""empty message

Revision ID: ac1ebfc56069
Revises: 3fc5cee2eeaf
Create Date: 2020-01-27 02:59:38.329205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1ebfc56069'
down_revision = '3fc5cee2eeaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('losses', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('wins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'wins')
    op.drop_column('team', 'losses')
    # ### end Alembic commands ###
