"""empty message

Revision ID: b2f4edcc9dd0
Revises: a71f95a4ec39
Create Date: 2019-11-28 21:05:21.200503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f4edcc9dd0'
down_revision = 'a71f95a4ec39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('away_team_short', sa.String(length=3), nullable=True))
    op.add_column('game', sa.Column('home_team_short', sa.String(length=3), nullable=True))
    op.create_unique_constraint(None, 'game', ['home_team_short', 'away_team_short', 'date'])
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'team', ['home_team_short'], ['short_name'])
    op.create_foreign_key(None, 'game', 'team', ['away_team_short'], ['short_name'])
    op.drop_column('game', 'home_team')
    op.drop_column('game', 'away_team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('away_team', sa.VARCHAR(length=3), nullable=True))
    op.add_column('game', sa.Column('home_team', sa.VARCHAR(length=3), nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'team', ['home_team'], ['short_name'])
    op.create_foreign_key(None, 'game', 'team', ['away_team'], ['short_name'])
    op.drop_constraint(None, 'game', type_='unique')
    op.drop_column('game', 'home_team_short')
    op.drop_column('game', 'away_team_short')
    # ### end Alembic commands ###
