"""empty message

Revision ID: c4e1e60b975d
Revises: 3fc5cee2eeaf
Create Date: 2019-12-12 23:31:58.072686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e1e60b975d'
down_revision = '3fc5cee2eeaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('date_time', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_bet_date_time'), 'bet', ['date_time'], unique=False)
    op.drop_index('ix_bet_timestamp', table_name='bet')
    op.drop_column('bet', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_bet_timestamp', 'bet', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_bet_date_time'), table_name='bet')
    op.drop_column('bet', 'date_time')
    # ### end Alembic commands ###
