"""empty message

Revision ID: e048f166c7b3
Revises: 0bb4475ddab9
Create Date: 2019-11-30 19:32:38.410628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e048f166c7b3'
down_revision = '0bb4475ddab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('odds', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('ranking_funds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ranking_funds')
    op.drop_column('bet', 'odds')
    # ### end Alembic commands ###
